data:
  image_folder: "/media/nhannvt/DATA/DOC/dataset/fisheye1k"              
  output_json: "../results/predictions.json"
models:
  models_folder: "../model"          
  max_workers: 4                            
model_configs:
  dfine:
    imgsz: 640

inference:
  use_ensemble: true                      
  resize_dimensions: [640, 640]          
  max_fps: 25.0                             # FPS for normalization

output:
  use_filename_as_id: true                  
  indent_json: 2                            

# Model Ensemble Router Configuration
# This configuration file defines all model settings, thresholds, and class mappings

# Model-specific configurations


# COCO class mapping (adjust based on your dataset)
class_mapping:
  0: "bus"
  1: "bike"
  2: "car"
  3: "pedestrian"
  4: "truck"

# Confidence thresholds for DFINE models
dfine_thresholds_config:
  # Thresholds for 640x640 DFINE models
  # Example thresholds for a 640x640 DFINE model (adjust as needed)
  640: [0.8, 0.8, 0.8, 0.7, 0.7]
  
# Threading configuration
max_workers: 4