data:
  image_folder: "/home/nhannvt/python_ws/challenge_iccv_2025/data"              
  output_json: "../results/predictions.json"   
  ground_truths_path: ""  #ground truth COCO-style for metrics calculation (optionial)

models:
  models_folder: "../model"          
  single_model_path: "../model/fisheye8k.onnx"      
  max_workers: 4                            

inference:
  use_ensemble: true                       # true: dùng ensemble, false: dùng mô hình đơn
  resize_dimensions: [1024, 1024]          
  max_fps: 25.0                             # FPS tối đa dùng để chuẩn hóa
  progress_interval: 50                     # Số ảnh mỗi lần in tiến trình

logging:
  show_performance_stats: true              # Hiện thống kê hiệu năng
  show_detailed_errors: true                # In lỗi chi tiết khi inference

output:
  use_filename_as_id: true                  # Dùng tên file làm ID ảnh khi xuất JSON
  indent_json: 2                            # Thụt dòng trong JSON xuất ra
