# Model Ensemble Router Configuration
# This configuration file defines all model settings, thresholds, and class mappings

# Model-specific configurations
model_configs:
  dfine:
    imgsz: 1024
runtime_engine: 'TRT' # 'TRT' for tensorRT | 'ONNX' for onnxruntime
# class mapping
class_mapping:
  0: "bus"
  1: "bike"
  2: "car"
  3: "pedestrian"
  4: "truck"

dfine_thresholds_config:
  # Thresholds for 1024x1024 DFINE models
  # Example thresholds for a 1024x1024 DFINE model (adjust as needed)
  1024: [0.8, 0.8, 0.8, 0.7, 0.7]
  
# Threading configuration
max_workers: 4