# Model Ensemble Router Configuration
# This configuration file defines all model settings, thresholds, and class mappings

# Model-specific configurations
model_configs:
  dfine:
    imgsz: 1024

# Class-specific configurations
class_specific_configs:
  truck:
    imgsz: 1024
  bus:
    imgsz: 1024
  bike:
    imgsz: 1024
  pedestrian:
    imgsz: 1024
  motorcycle:
    imgsz: 1024
  bicycle:
    imgsz: 1024

# COCO class mapping (adjust based on your dataset)
class_mapping:
  0: "bus"
  1: "bike"
  2: "car"
  3: "pedestrian"
  4: "truck"

# Confidence thresholds for DFINE models
dfine_thresholds_config:
  # Thresholds for 1024x1024 DFINE models
  # Example thresholds for a 1024x1024 DFINE model (adjust as needed)
  1024: [0.8, 0.8, 0.8, 0.7, 0.7]
  
# Threading configuration
max_workers: 4